ALTER TABLE "TraderProfile"
  ADD COLUMN "username" TEXT,
  ADD COLUMN "country" TEXT,
  ADD COLUMN "timezone" TEXT,
  ADD COLUMN "profilePictureUrl" TEXT,
  ADD COLUMN "traderType" TEXT,
  ADD COLUMN "brokers" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "propFirms" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "liveAccountSize" INTEGER,
  ADD COLUMN "propAccountSize" INTEGER,
  ADD COLUMN "challengeSize" INTEGER,
  ADD COLUMN "tradingStyle" TEXT,
  ADD COLUMN "goals" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "targetMonthlyPercent" DECIMAL(65,30),
  ADD COLUMN "targetMonthlyProfit" DECIMAL(65,30),
  ADD COLUMN "targetWinRate" DECIMAL(65,30),
  ADD COLUMN "sessions" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "favoriteAssets" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "yearsExperience" DECIMAL(65,30),
  ADD COLUMN "propChallenges" INTEGER,
  ADD COLUMN "fundedBefore" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "largestAccount" INTEGER,
  ADD COLUMN "psychologyWeaknesses" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "personality" JSONB,
  ADD COLUMN "preferences" JSONB,
  ADD COLUMN "connectedAccounts" JSONB,
  ADD COLUMN "performance" JSONB;
