export type BrokerScore = {
  regulation: number;
  execution: number;
  spreads: number;
  withdrawals: number;
  support: number;
  platforms: number;
  transparency: number;
};

export type BrokerInstrument = {
  symbol: string;
  averageSpread: string;
  minimumSpread: string;
  commission: string;
  leverage: string;
};

export type Broker = {
  name: string;
  slug: string;
  domain: string;
  logoUrl: string;
  logoFallback: string;
  founded: string;
  headquarters: string;
  regulators: string[];
  trustScore: number;
  verifiedStatus: "Verified baseline" | "Research queue" | "Needs source review";
  lastVerified: string;
  markets: string[];
  accountTypes: string[];
  platforms: string[];
  features: string[];
  deposits: string[];
  withdrawals: string[];
  support: string[];
  supportHours: string;
  languages: string;
  supportEmail: string;
  score: BrokerScore;
  instruments: BrokerInstrument[];
  bestFor: string;
};

const defaultInstruments: BrokerInstrument[] = [
  { symbol: "XAUUSD", averageSpread: "Not live yet", minimumSpread: "Needs official source", commission: "Account based", leverage: "Region based" },
  { symbol: "EURUSD", averageSpread: "Not live yet", minimumSpread: "Needs official source", commission: "Account based", leverage: "Region based" },
  { symbol: "NAS100", averageSpread: "Not live yet", minimumSpread: "Needs official source", commission: "Account based", leverage: "Region based" }
];

function broker(domain: string, data: Omit<Broker, "domain" | "logoUrl" | "instruments"> & { instruments?: BrokerInstrument[] }): Broker {
  return {
    ...data,
    domain,
    logoUrl: `https://www.google.com/s2/favicons?domain=${domain}&sz=128`,
    instruments: data.instruments ?? defaultInstruments
  };
}

export const brokers: Broker[] = [
  broker("exness.com", {
    name: "Exness",
    slug: "exness",
    logoFallback: "EX",
    founded: "2008",
    headquarters: "Limassol, Cyprus",
    regulators: ["FSA Seychelles", "CySEC", "FCA entity", "FSCA"],
    trustScore: 95,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Metals", "Crypto", "Indices", "Stocks", "Energies"],
    accountTypes: ["Standard", "Standard Cent", "Raw Spread", "Zero", "Pro", "Demo"],
    platforms: ["MT4", "MT5", "WebTerminal", "Mobile App"],
    features: ["Copy trading", "EA support", "Scalping", "Hedging", "VPS"],
    deposits: ["Bank card", "Bank transfer", "Crypto", "Skrill", "Neteller"],
    withdrawals: ["Bank card", "Bank transfer", "Crypto", "E-wallets"],
    support: ["Live chat", "Help center", "Email"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@exness.com",
    score: { regulation: 92, execution: 94, spreads: 95, withdrawals: 96, support: 91, platforms: 92, transparency: 90 },
    bestFor: "Gold, crypto and high-frequency CFD traders who care about flexible account types"
  }),
  broker("icmarkets.com", {
    name: "IC Markets",
    slug: "ic-markets",
    logoFallback: "IC",
    founded: "2007",
    headquarters: "Sydney, Australia",
    regulators: ["ASIC", "CySEC", "FSA Seychelles"],
    trustScore: 94,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Crypto", "Bonds"],
    accountTypes: ["Standard", "Raw Spread", "Islamic", "Demo"],
    platforms: ["MT4", "MT5", "cTrader", "TradingView"],
    features: ["Raw spreads", "EA support", "Scalping", "VPS", "Copy trading"],
    deposits: ["Card", "Bank transfer", "PayPal", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Help center"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@icmarkets.com",
    score: { regulation: 94, execution: 95, spreads: 96, withdrawals: 90, support: 88, platforms: 96, transparency: 91 },
    bestFor: "Raw spread traders, scalpers and traders comparing execution cost"
  }),
  broker("pepperstone.com", {
    name: "Pepperstone",
    slug: "pepperstone",
    logoFallback: "PS",
    founded: "2010",
    headquarters: "Melbourne, Australia",
    regulators: ["ASIC", "FCA", "CySEC", "DFSA", "BaFin"],
    trustScore: 94,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Crypto", "Shares"],
    accountTypes: ["Standard", "Razor", "Swap-free", "Demo"],
    platforms: ["MT4", "MT5", "cTrader", "TradingView"],
    features: ["TradingView", "EA support", "Scalping", "Copy trading"],
    deposits: ["Card", "Bank transfer", "PayPal", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@pepperstone.com",
    score: { regulation: 96, execution: 94, spreads: 93, withdrawals: 90, support: 90, platforms: 97, transparency: 93 },
    bestFor: "Regulation-conscious CFD traders who want MT4, MT5, cTrader and TradingView"
  }),
  broker("vantage.com", {
    name: "Vantage",
    slug: "vantage",
    logoFallback: "VG",
    founded: "2009",
    headquarters: "Sydney, Australia",
    regulators: ["ASIC", "CIMA", "VFSC"],
    trustScore: 88,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Indices", "Metals", "Commodities", "Shares", "Crypto"],
    accountTypes: ["Standard STP", "Raw ECN", "Pro ECN", "Demo"],
    platforms: ["MT4", "MT5", "TradingView", "Mobile App"],
    features: ["Copy trading", "EA support", "TradingView", "VPS"],
    deposits: ["Card", "Bank transfer", "E-wallets", "Crypto"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@vantage.com",
    score: { regulation: 86, execution: 88, spreads: 89, withdrawals: 86, support: 85, platforms: 91, transparency: 84 },
    bestFor: "Traders who want broad CFD coverage and account choice"
  }),
  broker("eightcap.com", {
    name: "Eightcap",
    slug: "eightcap",
    logoFallback: "8C",
    founded: "2009",
    headquarters: "Melbourne, Australia",
    regulators: ["ASIC", "FCA", "CySEC", "SCB"],
    trustScore: 89,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Crypto", "Indices", "Commodities", "Shares"],
    accountTypes: ["Standard", "Raw", "TradingView", "Demo"],
    platforms: ["MT4", "MT5", "TradingView"],
    features: ["Crypto CFDs", "TradingView", "EA support", "Scalping"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller", "Crypto"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@eightcap.com",
    score: { regulation: 90, execution: 88, spreads: 87, withdrawals: 86, support: 84, platforms: 92, transparency: 86 },
    bestFor: "Crypto CFD and TradingView-focused traders"
  }),
  broker("tickmill.com", {
    name: "Tickmill",
    slug: "tickmill",
    logoFallback: "TM",
    founded: "2014",
    headquarters: "London, United Kingdom",
    regulators: ["FCA", "CySEC", "FSA Seychelles", "FSCA"],
    trustScore: 90,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Indices", "Metals", "Bonds", "Commodities", "Crypto"],
    accountTypes: ["Classic", "Raw", "Demo"],
    platforms: ["MT4", "MT5", "Mobile App"],
    features: ["Low commission", "EA support", "Scalping", "VPS"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@tickmill.com",
    score: { regulation: 91, execution: 89, spreads: 91, withdrawals: 88, support: 86, platforms: 85, transparency: 88 },
    bestFor: "Forex traders who care about low-cost execution"
  }),
  broker("fpmarkets.com", {
    name: "FP Markets",
    slug: "fp-markets",
    logoFallback: "FP",
    founded: "2005",
    headquarters: "Sydney, Australia",
    regulators: ["ASIC", "CySEC", "FSCA", "FSA Seychelles"],
    trustScore: 90,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Shares", "Crypto"],
    accountTypes: ["Standard", "Raw", "Islamic", "Demo"],
    platforms: ["MT4", "MT5", "cTrader", "TradingView", "IRESS"],
    features: ["Raw spreads", "Copy trading", "VPS", "EA support"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@fpmarkets.com",
    score: { regulation: 91, execution: 90, spreads: 90, withdrawals: 88, support: 88, platforms: 93, transparency: 88 },
    bestFor: "Multi-platform traders comparing raw and standard accounts"
  }),
  broker("fusionmarkets.com", {
    name: "Fusion Markets",
    slug: "fusion-markets",
    logoFallback: "FM",
    founded: "2017",
    headquarters: "Melbourne, Australia",
    regulators: ["ASIC", "VFSC", "FSA Seychelles"],
    trustScore: 86,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Crypto"],
    accountTypes: ["Classic", "Zero", "Demo"],
    platforms: ["MT4", "MT5", "cTrader"],
    features: ["Low commission", "EA support", "Scalping"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/5 support advertised by broker",
    languages: "English support baseline",
    supportEmail: "help@fusionmarkets.com",
    score: { regulation: 84, execution: 87, spreads: 92, withdrawals: 84, support: 82, platforms: 86, transparency: 84 },
    bestFor: "Cost-sensitive FX and CFD traders"
  }),
  broker("oanda.com", {
    name: "OANDA",
    slug: "oanda",
    logoFallback: "OA",
    founded: "1996",
    headquarters: "New York, United States",
    regulators: ["CFTC/NFA", "FCA", "ASIC", "CIRO", "MAS"],
    trustScore: 93,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Bonds"],
    accountTypes: ["Standard", "Premium", "Demo"],
    platforms: ["OANDA Web", "MT4", "TradingView", "Mobile App"],
    features: ["Research tools", "TradingView", "API", "Institutional history"],
    deposits: ["Card", "Bank transfer", "PayPal"],
    withdrawals: ["Bank transfer", "Card"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "Region based support hours",
    languages: "Multi-language support",
    supportEmail: "frontdesk@oanda.com",
    score: { regulation: 97, execution: 88, spreads: 84, withdrawals: 87, support: 88, platforms: 88, transparency: 94 },
    bestFor: "Regulation-first forex traders and researchers"
  }),
  broker("forex.com", {
    name: "FOREX.com",
    slug: "forex-com",
    logoFallback: "FX",
    founded: "2001",
    headquarters: "United States / StoneX Group",
    regulators: ["CFTC/NFA", "FCA", "CIRO", "ASIC", "MAS"],
    trustScore: 92,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Indices", "Commodities", "Shares", "Crypto CFDs"],
    accountTypes: ["Standard", "RAW Pricing", "MetaTrader", "Demo"],
    platforms: ["FOREX.com Web", "MT4", "MT5", "TradingView", "Mobile App"],
    features: ["Research", "TradingView", "Market analysis", "Education"],
    deposits: ["Card", "Bank transfer", "PayPal"],
    withdrawals: ["Bank transfer", "Card"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "Region based support hours",
    languages: "Multi-language support",
    supportEmail: "support@forex.com",
    score: { regulation: 96, execution: 88, spreads: 84, withdrawals: 86, support: 87, platforms: 90, transparency: 93 },
    bestFor: "US/regulated-market forex traders"
  }),
  broker("cmcmarkets.com", {
    name: "CMC Markets",
    slug: "cmc-markets",
    logoFallback: "CM",
    founded: "1989",
    headquarters: "London, United Kingdom",
    regulators: ["FCA", "ASIC", "CIRO", "MAS", "FMA"],
    trustScore: 93,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Indices", "Commodities", "Shares", "Treasuries", "Crypto CFDs"],
    accountTypes: ["CFD", "Spread Betting", "Professional", "Demo"],
    platforms: ["Next Generation", "MT4", "Mobile App"],
    features: ["Research", "Advanced platform", "Large instrument range"],
    deposits: ["Card", "Bank transfer"],
    withdrawals: ["Bank transfer", "Card"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "Region based support hours",
    languages: "Multi-language support",
    supportEmail: "clientmanagement@cmcmarkets.com",
    score: { regulation: 96, execution: 88, spreads: 86, withdrawals: 86, support: 88, platforms: 91, transparency: 93 },
    bestFor: "Regulated CFD traders who want a broad instrument universe"
  }),
  broker("ig.com", {
    name: "IG",
    slug: "ig",
    logoFallback: "IG",
    founded: "1974",
    headquarters: "London, United Kingdom",
    regulators: ["FCA", "ASIC", "CFTC/NFA", "MAS", "BaFin"],
    trustScore: 96,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Indices", "Commodities", "Shares", "Options", "Crypto CFDs"],
    accountTypes: ["CFD", "Spread Betting", "Professional", "Demo"],
    platforms: ["IG Platform", "MT4", "ProRealTime", "L2 Dealer", "Mobile App"],
    features: ["Research", "Education", "Advanced charting", "Large market coverage"],
    deposits: ["Card", "Bank transfer", "PayPal"],
    withdrawals: ["Bank transfer", "Card", "PayPal"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24-hour dealing/support by region",
    languages: "Multi-language support",
    supportEmail: "helpdesk@ig.com",
    score: { regulation: 98, execution: 90, spreads: 86, withdrawals: 88, support: 90, platforms: 94, transparency: 95 },
    bestFor: "Trust-focused traders who want a large, regulated broker"
  }),
  broker("xm.com", {
    name: "XM",
    slug: "xm",
    logoFallback: "XM",
    founded: "2009",
    headquarters: "Cyprus",
    regulators: ["CySEC", "ASIC", "FSC Belize", "DFSA"],
    trustScore: 84,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Shares"],
    accountTypes: ["Micro", "Standard", "Ultra Low", "Shares", "Demo"],
    platforms: ["MT4", "MT5", "Mobile App"],
    features: ["Education", "Bonuses by region", "EA support"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@xm.com",
    score: { regulation: 82, execution: 83, spreads: 82, withdrawals: 84, support: 86, platforms: 84, transparency: 82 },
    bestFor: "Beginner CFD traders who value education and account variety"
  }),
  broker("hfm.com", {
    name: "HFM",
    slug: "hfm",
    logoFallback: "HF",
    founded: "2010",
    headquarters: "Cyprus",
    regulators: ["FCA", "CySEC", "DFSA", "FSCA", "FSA Seychelles"],
    trustScore: 85,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Shares", "Crypto"],
    accountTypes: ["Cent", "Premium", "Zero", "Pro", "Demo"],
    platforms: ["MT4", "MT5", "Mobile App"],
    features: ["Copy trading", "Education", "EA support", "VPS"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller", "Crypto"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@hfm.com",
    score: { regulation: 85, execution: 84, spreads: 84, withdrawals: 84, support: 84, platforms: 84, transparency: 82 },
    bestFor: "Multi-account CFD traders in international markets"
  }),
  broker("avatrade.com", {
    name: "AvaTrade",
    slug: "avatrade",
    logoFallback: "AV",
    founded: "2006",
    headquarters: "Dublin, Ireland",
    regulators: ["Central Bank of Ireland", "ASIC", "FSCA", "FSA Japan", "ADGM"],
    trustScore: 87,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Commodities", "Indices", "Shares", "Options", "Crypto CFDs"],
    accountTypes: ["Retail", "Professional", "Islamic", "Demo"],
    platforms: ["AvaTradeGO", "MT4", "MT5", "AvaOptions", "WebTrader"],
    features: ["Options", "Copy trading", "Education", "Fixed spreads by region"],
    deposits: ["Card", "Bank transfer", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "cs@avatrade.com",
    score: { regulation: 89, execution: 82, spreads: 80, withdrawals: 83, support: 85, platforms: 87, transparency: 85 },
    bestFor: "Multi-asset traders who want broad platform choice"
  }),
  broker("xtb.com", {
    name: "XTB",
    slug: "xtb",
    logoFallback: "XT",
    founded: "2002",
    headquarters: "Warsaw, Poland",
    regulators: ["KNF", "FCA", "CySEC", "DFSA"],
    trustScore: 90,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Indices", "Commodities", "Shares", "ETFs", "Crypto CFDs"],
    accountTypes: ["Standard", "Professional", "Demo"],
    platforms: ["xStation", "Mobile App"],
    features: ["xStation", "Stocks/ETFs by region", "Education", "Research"],
    deposits: ["Card", "Bank transfer", "PayPal"],
    withdrawals: ["Bank transfer"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@xtb.com",
    score: { regulation: 92, execution: 86, spreads: 84, withdrawals: 86, support: 87, platforms: 88, transparency: 90 },
    bestFor: "xStation users and traders who want a listed European broker"
  }),
  broker("admiralmarkets.com", {
    name: "Admirals",
    slug: "admirals",
    logoFallback: "AD",
    founded: "2001",
    headquarters: "Tallinn, Estonia",
    regulators: ["FCA", "CySEC", "ASIC", "EFSA"],
    trustScore: 88,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Indices", "Commodities", "Shares", "ETFs", "Bonds"],
    accountTypes: ["Trade", "Zero", "Invest", "Demo"],
    platforms: ["MT4", "MT5", "WebTrader", "Mobile App"],
    features: ["MT5 Supreme Edition", "Invest account", "Education"],
    deposits: ["Card", "Bank transfer", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "global@admiralmarkets.com",
    score: { regulation: 90, execution: 85, spreads: 84, withdrawals: 84, support: 85, platforms: 88, transparency: 88 },
    bestFor: "MT4/MT5 traders who want CFDs plus investing tools"
  }),
  broker("swissquote.com", {
    name: "Swissquote",
    slug: "swissquote",
    logoFallback: "SQ",
    founded: "1996",
    headquarters: "Gland, Switzerland",
    regulators: ["FINMA", "FCA", "DFSA", "MAS"],
    trustScore: 94,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Stocks", "ETFs", "Funds", "Bonds", "Crypto"],
    accountTypes: ["Trading", "Forex", "Professional", "Demo"],
    platforms: ["Advanced Trader", "MT4", "MT5", "Mobile App"],
    features: ["Swiss bank", "Research", "Multi-asset investing"],
    deposits: ["Bank transfer", "Card"],
    withdrawals: ["Bank transfer"],
    support: ["Email", "Phone"],
    supportHours: "Banking/business hours by region",
    languages: "Multi-language support",
    supportEmail: "info@swissquote.com",
    score: { regulation: 98, execution: 86, spreads: 80, withdrawals: 86, support: 84, platforms: 86, transparency: 95 },
    bestFor: "Safety-first traders who want bank-grade infrastructure"
  }),
  broker("home.saxo", {
    name: "Saxo",
    slug: "saxo",
    logoFallback: "SX",
    founded: "1992",
    headquarters: "Copenhagen, Denmark",
    regulators: ["Danish FSA", "FCA", "FINMA", "ASIC", "MAS"],
    trustScore: 95,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Stocks", "ETFs", "Bonds", "Options", "Futures", "CFDs"],
    accountTypes: ["Classic", "Platinum", "VIP", "Professional"],
    platforms: ["SaxoTraderGO", "SaxoTraderPRO", "Mobile App"],
    features: ["Institutional platform", "Research", "Multi-asset coverage", "Options/futures"],
    deposits: ["Bank transfer", "Card by region"],
    withdrawals: ["Bank transfer"],
    support: ["Email", "Phone", "Help center"],
    supportHours: "Business hours by region",
    languages: "Multi-language support",
    supportEmail: "service@saxo.com",
    score: { regulation: 98, execution: 90, spreads: 82, withdrawals: 86, support: 86, platforms: 95, transparency: 94 },
    bestFor: "Serious multi-asset traders and investors"
  }),
  broker("axi.com", {
    name: "Axi",
    slug: "axi",
    logoFallback: "AX",
    founded: "2007",
    headquarters: "Sydney, Australia",
    regulators: ["ASIC", "FCA", "DFSA", "FMA"],
    trustScore: 88,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Crypto CFDs"],
    accountTypes: ["Standard", "Pro", "Elite", "Demo"],
    platforms: ["MT4", "Mobile App"],
    features: ["Copy trading", "EA support", "VPS", "MT4 specialist"],
    deposits: ["Card", "Bank transfer", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "service@axi.com",
    score: { regulation: 90, execution: 86, spreads: 86, withdrawals: 84, support: 85, platforms: 82, transparency: 86 },
    bestFor: "MT4-focused forex and index traders"
  }),
  broker("fxtm.com", {
    name: "FXTM",
    slug: "fxtm",
    logoFallback: "FT",
    founded: "2011",
    headquarters: "Limassol, Cyprus",
    regulators: ["FCA", "CySEC", "FSCA", "FSC Mauritius"],
    trustScore: 84,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Stocks"],
    accountTypes: ["Advantage", "Advantage Plus", "Demo"],
    platforms: ["MT4", "MT5", "Mobile App"],
    features: ["Education", "Copy trading by region", "EA support"],
    deposits: ["Card", "Bank transfer", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@fxtm.com",
    score: { regulation: 85, execution: 83, spreads: 82, withdrawals: 82, support: 84, platforms: 84, transparency: 82 },
    bestFor: "Education-led forex traders in supported regions"
  }),
  broker("fxpro.com", {
    name: "FxPro",
    slug: "fxpro",
    logoFallback: "FP",
    founded: "2006",
    headquarters: "London, United Kingdom",
    regulators: ["FCA", "CySEC", "FSCA", "SCB"],
    trustScore: 89,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Metals", "Indices", "Energies", "Shares", "Crypto CFDs"],
    accountTypes: ["Standard", "Raw+", "Elite", "Demo"],
    platforms: ["MT4", "MT5", "cTrader", "FxPro Platform"],
    features: ["cTrader", "EA support", "Scalping", "VPS"],
    deposits: ["Card", "Bank transfer", "PayPal", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@fxpro.com",
    score: { regulation: 91, execution: 88, spreads: 86, withdrawals: 86, support: 86, platforms: 91, transparency: 88 },
    bestFor: "Traders who want MT4, MT5 and cTrader under one broker"
  }),
  broker("blackbull.com", {
    name: "BlackBull Markets",
    slug: "blackbull-markets",
    logoFallback: "BB",
    founded: "2014",
    headquarters: "Auckland, New Zealand",
    regulators: ["FMA New Zealand", "FSA Seychelles"],
    trustScore: 86,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Shares", "Crypto CFDs"],
    accountTypes: ["ECN Standard", "ECN Prime", "ECN Institutional", "Demo"],
    platforms: ["MT4", "MT5", "TradingView", "cTrader"],
    features: ["ECN accounts", "TradingView", "Copy trading", "VPS"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@blackbull.com",
    score: { regulation: 84, execution: 88, spreads: 88, withdrawals: 84, support: 86, platforms: 93, transparency: 84 },
    bestFor: "TradingView and ECN-style traders"
  }),
  broker("thinkmarkets.com", {
    name: "ThinkMarkets",
    slug: "thinkmarkets",
    logoFallback: "TH",
    founded: "2010",
    headquarters: "London, United Kingdom",
    regulators: ["FCA", "ASIC", "CySEC", "FSA Seychelles", "FSCA"],
    trustScore: 88,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Indices", "Metals", "Commodities", "Shares", "Crypto CFDs"],
    accountTypes: ["Standard", "ThinkZero", "Islamic", "Demo"],
    platforms: ["ThinkTrader", "MT4", "MT5"],
    features: ["ThinkTrader", "EA support", "Education", "Trading tools"],
    deposits: ["Card", "Bank transfer", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@thinkmarkets.com",
    score: { regulation: 90, execution: 86, spreads: 85, withdrawals: 84, support: 85, platforms: 88, transparency: 86 },
    bestFor: "Traders who want proprietary apps plus MetaTrader"
  }),
  broker("deriv.com", {
    name: "Deriv",
    slug: "deriv",
    logoFallback: "DV",
    founded: "1999",
    headquarters: "Multi-jurisdiction",
    regulators: ["MFSA", "Labuan FSA", "VFSC", "BVI FSC"],
    trustScore: 82,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Synthetic indices", "Commodities", "Stocks", "Crypto"],
    accountTypes: ["CFD", "Derived", "Financial", "Demo"],
    platforms: ["Deriv Trader", "Deriv X", "MT5", "cTrader", "Bot"],
    features: ["Synthetic indices", "Bot trading", "24/7 markets", "MT5"],
    deposits: ["Card", "Bank transfer", "Crypto", "E-wallets"],
    withdrawals: ["Bank transfer", "Crypto", "E-wallets"],
    support: ["Live chat", "Help center", "Community"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@deriv.com",
    score: { regulation: 78, execution: 84, spreads: 82, withdrawals: 82, support: 82, platforms: 90, transparency: 80 },
    bestFor: "Synthetic-index traders and 24/7 market access"
  }),
  broker("fbs.com", {
    name: "FBS",
    slug: "fbs",
    logoFallback: "FB",
    founded: "2009",
    headquarters: "Belize / Cyprus entities",
    regulators: ["CySEC", "FSC Belize", "ASIC entity"],
    trustScore: 81,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Metals", "Indices", "Energies", "Stocks", "Crypto"],
    accountTypes: ["Standard", "Cent", "Pro", "Demo"],
    platforms: ["MT4", "MT5", "FBS App"],
    features: ["Education", "Promotions by region", "Copy/social tools by region"],
    deposits: ["Card", "Bank transfer", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@fbs.com",
    score: { regulation: 78, execution: 80, spreads: 80, withdrawals: 80, support: 83, platforms: 82, transparency: 78 },
    bestFor: "Beginner traders in supported international markets"
  }),
  broker("tradenation.com", {
    name: "Trade Nation",
    slug: "trade-nation",
    logoFallback: "TN",
    founded: "2014",
    headquarters: "London, United Kingdom",
    regulators: ["FCA", "ASIC", "FSCA", "SCB"],
    trustScore: 86,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Indices", "Commodities", "Shares", "Bonds"],
    accountTypes: ["Retail", "Professional", "Demo"],
    platforms: ["Trade Nation Platform", "TradingView", "MT4"],
    features: ["Fixed spread model by market", "TradingView", "Education"],
    deposits: ["Card", "Bank transfer"],
    withdrawals: ["Bank transfer", "Card"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "English support baseline",
    supportEmail: "support@tradenation.com",
    score: { regulation: 90, execution: 84, spreads: 82, withdrawals: 84, support: 84, platforms: 86, transparency: 86 },
    bestFor: "Traders who prefer simple pricing and regulated entities"
  }),
  broker("plus500.com", {
    name: "Plus500",
    slug: "plus500",
    logoFallback: "P5",
    founded: "2008",
    headquarters: "Israel / London-listed group",
    regulators: ["FCA", "ASIC", "CySEC", "MAS", "FMA"],
    trustScore: 90,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Forex", "Indices", "Commodities", "Shares", "Options", "Crypto CFDs"],
    accountTypes: ["Retail CFD", "Professional", "Demo"],
    platforms: ["Plus500 WebTrader", "Mobile App"],
    features: ["Simple platform", "Risk controls", "Large CFD list"],
    deposits: ["Card", "Bank transfer", "PayPal", "Skrill"],
    withdrawals: ["Bank transfer", "Card", "PayPal", "Skrill"],
    support: ["Live chat", "Email"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@plus500.com",
    score: { regulation: 94, execution: 84, spreads: 80, withdrawals: 86, support: 84, platforms: 80, transparency: 88 },
    bestFor: "Simple CFD trading with strong public-company/regulatory footprint"
  }),
  broker("interactivebrokers.com", {
    name: "Interactive Brokers",
    slug: "interactive-brokers",
    logoFallback: "IB",
    founded: "1978",
    headquarters: "Greenwich, United States",
    regulators: ["SEC/FINRA", "CFTC/NFA", "FCA", "ASIC", "MAS"],
    trustScore: 97,
    verifiedStatus: "Research queue",
    lastVerified: "Pending official source review",
    markets: ["Stocks", "Options", "Futures", "Forex", "Bonds", "Funds", "Crypto by region"],
    accountTypes: ["Individual", "Professional", "Institutional", "Demo"],
    platforms: ["Trader Workstation", "IBKR Desktop", "Client Portal", "Mobile App"],
    features: ["Professional platform", "Global markets", "API", "Institutional-grade execution"],
    deposits: ["Bank transfer", "ACH by region"],
    withdrawals: ["Bank transfer", "ACH by region"],
    support: ["Ticket", "Phone", "Chat by region"],
    supportHours: "Region based support hours",
    languages: "Multi-language support",
    supportEmail: "help@interactivebrokers.com",
    score: { regulation: 99, execution: 94, spreads: 86, withdrawals: 88, support: 84, platforms: 96, transparency: 96 },
    bestFor: "Advanced traders who need global market access and professional tools"
  })
];

export const brokerScoreWeights = [
  ["Regulation", 18],
  ["Execution", 15],
  ["Spreads", 15],
  ["Withdrawals", 12],
  ["Support", 10],
  ["Platforms", 10],
  ["Transparency", 8],
  ["Safety", 7],
  ["Commissions", 3],
  ["Community", 2]
] as const;

export const brokerStats = {
  brokers: brokers.length,
  regulators: new Set(brokers.flatMap((brokerItem) => brokerItem.regulators)).size,
  instruments: new Set(brokers.flatMap((brokerItem) => brokerItem.instruments.map((instrument) => instrument.symbol))).size,
  platforms: new Set(brokers.flatMap((brokerItem) => brokerItem.platforms)).size
};
