export type BrokerScore = {
  regulation: number;
  execution: number;
  spreads: number;
  withdrawals: number;
  support: number;
  platforms: number;
  transparency: number;
};

export type BrokerInstrument = {
  symbol: string;
  averageSpread: string;
  minimumSpread: string;
  commission: string;
  leverage: string;
};

export type Broker = {
  name: string;
  slug: string;
  domain: string;
  logoUrl: string;
  logoFallback: string;
  founded: string;
  headquarters: string;
  regulators: string[];
  trustScore: number;
  verifiedStatus: "Verified profile" | "Source-reviewed" | "Verification required";
  lastVerified: string;
  markets: string[];
  accountTypes: string[];
  platforms: string[];
  features: string[];
  deposits: string[];
  withdrawals: string[];
  support: string[];
  supportHours: string;
  languages: string;
  supportEmail: string;
  score: BrokerScore;
  instruments: BrokerInstrument[];
  bestFor: string;
};

export type BrokerConfidenceRow = {
  key: string;
  label: string;
  value: number;
  max: number;
  explanation: string;
};

export type BrokerConfidenceBreakdown = {
  total: number;
  max: number;
  label: string;
  formula: string;
  rows: BrokerConfidenceRow[];
  lastReviewed: string;
  dataWarning: string;
};

const defaultInstruments: BrokerInstrument[] = [
  { symbol: "XAUUSD", averageSpread: "Not published", minimumSpread: "Official source required", commission: "Account based", leverage: "Region based" },
  { symbol: "EURUSD", averageSpread: "Not published", minimumSpread: "Official source required", commission: "Account based", leverage: "Region based" },
  { symbol: "NAS100", averageSpread: "Not published", minimumSpread: "Official source required", commission: "Account based", leverage: "Region based" }
];

function broker(domain: string, data: Omit<Broker, "domain" | "logoUrl" | "instruments"> & { instruments?: BrokerInstrument[] }): Broker {
  return {
    ...data,
    domain,
    logoUrl: `https://logo.clearbit.com/${domain}`,
    instruments: data.instruments ?? defaultInstruments
  };
}

export const brokers: Broker[] = [
  broker("exness.com", {
    name: "Exness",
    slug: "exness",
    logoFallback: "EX",
    founded: "2008",
    headquarters: "Limassol, Cyprus",
    regulators: ["FSA Seychelles", "CySEC", "FCA entity", "FSCA"],
    trustScore: 95,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Crypto", "Indices", "Stocks", "Energies"],
    accountTypes: ["Standard", "Standard Cent", "Raw Spread", "Zero", "Pro", "Demo"],
    platforms: ["MT4", "MT5", "WebTerminal", "Mobile App"],
    features: ["Copy trading", "EA support", "Scalping", "Hedging", "VPS"],
    deposits: ["Bank card", "Bank transfer", "Crypto", "Skrill", "Neteller"],
    withdrawals: ["Bank card", "Bank transfer", "Crypto", "E-wallets"],
    support: ["Live chat", "Help center", "Email"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@exness.com",
    score: { regulation: 92, execution: 94, spreads: 95, withdrawals: 96, support: 91, platforms: 92, transparency: 90 },
    bestFor: "Gold, crypto and high-frequency CFD traders who care about flexible account types"
  }),
  broker("icmarkets.com", {
    name: "IC Markets",
    slug: "ic-markets",
    logoFallback: "IC",
    founded: "2007",
    headquarters: "Sydney, Australia",
    regulators: ["ASIC", "CySEC", "FSA Seychelles"],
    trustScore: 94,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Crypto", "Bonds"],
    accountTypes: ["Standard", "Raw Spread", "Islamic", "Demo"],
    platforms: ["MT4", "MT5", "cTrader", "TradingView"],
    features: ["Raw spreads", "EA support", "Scalping", "VPS", "Copy trading"],
    deposits: ["Card", "Bank transfer", "PayPal", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Help center"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@icmarkets.com",
    score: { regulation: 94, execution: 95, spreads: 96, withdrawals: 90, support: 88, platforms: 96, transparency: 91 },
    bestFor: "Raw spread traders, scalpers and traders comparing execution cost"
  }),
  broker("pepperstone.com", {
    name: "Pepperstone",
    slug: "pepperstone",
    logoFallback: "PS",
    founded: "2010",
    headquarters: "Melbourne, Australia",
    regulators: ["ASIC", "FCA", "CySEC", "DFSA", "BaFin"],
    trustScore: 94,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Crypto", "Shares"],
    accountTypes: ["Standard", "Razor", "Swap-free", "Demo"],
    platforms: ["MT4", "MT5", "cTrader", "TradingView"],
    features: ["TradingView", "EA support", "Scalping", "Copy trading"],
    deposits: ["Card", "Bank transfer", "PayPal", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@pepperstone.com",
    score: { regulation: 96, execution: 94, spreads: 93, withdrawals: 90, support: 90, platforms: 97, transparency: 93 },
    bestFor: "Regulation-conscious CFD traders who want MT4, MT5, cTrader and TradingView"
  }),
  broker("vantage.com", {
    name: "Vantage",
    slug: "vantage",
    logoFallback: "VG",
    founded: "2009",
    headquarters: "Sydney, Australia",
    regulators: ["ASIC", "CIMA", "VFSC"],
    trustScore: 88,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Indices", "Metals", "Commodities", "Shares", "Crypto"],
    accountTypes: ["Standard STP", "Raw ECN", "Pro ECN", "Demo"],
    platforms: ["MT4", "MT5", "TradingView", "Mobile App"],
    features: ["Copy trading", "EA support", "TradingView", "VPS"],
    deposits: ["Card", "Bank transfer", "E-wallets", "Crypto"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@vantage.com",
    score: { regulation: 86, execution: 88, spreads: 89, withdrawals: 86, support: 85, platforms: 91, transparency: 84 },
    bestFor: "Traders who want broad CFD coverage and account choice"
  }),
  broker("eightcap.com", {
    name: "Eightcap",
    slug: "eightcap",
    logoFallback: "8C",
    founded: "2009",
    headquarters: "Melbourne, Australia",
    regulators: ["ASIC", "FCA", "CySEC", "SCB"],
    trustScore: 89,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Crypto", "Indices", "Commodities", "Shares"],
    accountTypes: ["Standard", "Raw", "TradingView", "Demo"],
    platforms: ["MT4", "MT5", "TradingView"],
    features: ["Crypto CFDs", "TradingView", "EA support", "Scalping"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller", "Crypto"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@eightcap.com",
    score: { regulation: 90, execution: 88, spreads: 87, withdrawals: 86, support: 84, platforms: 92, transparency: 86 },
    bestFor: "Crypto CFD and TradingView-focused traders"
  }),
  broker("tickmill.com", {
    name: "Tickmill",
    slug: "tickmill",
    logoFallback: "TM",
    founded: "2014",
    headquarters: "London, United Kingdom",
    regulators: ["FCA", "CySEC", "FSA Seychelles", "FSCA"],
    trustScore: 90,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Indices", "Metals", "Bonds", "Commodities", "Crypto"],
    accountTypes: ["Classic", "Raw", "Demo"],
    platforms: ["MT4", "MT5", "Mobile App"],
    features: ["Low commission", "EA support", "Scalping", "VPS"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@tickmill.com",
    score: { regulation: 91, execution: 89, spreads: 91, withdrawals: 88, support: 86, platforms: 85, transparency: 88 },
    bestFor: "Forex traders who care about low-cost execution"
  }),
  broker("fpmarkets.com", {
    name: "FP Markets",
    slug: "fp-markets",
    logoFallback: "FP",
    founded: "2005",
    headquarters: "Sydney, Australia",
    regulators: ["ASIC", "CySEC", "FSCA", "FSA Seychelles"],
    trustScore: 90,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Shares", "Crypto"],
    accountTypes: ["Standard", "Raw", "Islamic", "Demo"],
    platforms: ["MT4", "MT5", "cTrader", "TradingView", "IRESS"],
    features: ["Raw spreads", "Copy trading", "VPS", "EA support"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@fpmarkets.com",
    score: { regulation: 91, execution: 90, spreads: 90, withdrawals: 88, support: 88, platforms: 93, transparency: 88 },
    bestFor: "Multi-platform traders comparing raw and standard accounts"
  }),
  broker("fusionmarkets.com", {
    name: "Fusion Markets",
    slug: "fusion-markets",
    logoFallback: "FM",
    founded: "2017",
    headquarters: "Melbourne, Australia",
    regulators: ["ASIC", "VFSC", "FSA Seychelles"],
    trustScore: 86,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Crypto"],
    accountTypes: ["Classic", "Zero", "Demo"],
    platforms: ["MT4", "MT5", "cTrader"],
    features: ["Low commission", "EA support", "Scalping"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/5 support advertised by broker",
    languages: "English support baseline",
    supportEmail: "help@fusionmarkets.com",
    score: { regulation: 84, execution: 87, spreads: 92, withdrawals: 84, support: 82, platforms: 86, transparency: 84 },
    bestFor: "Cost-sensitive FX and CFD traders"
  }),
  broker("oanda.com", {
    name: "OANDA",
    slug: "oanda",
    logoFallback: "OA",
    founded: "1996",
    headquarters: "New York, United States",
    regulators: ["CFTC/NFA", "FCA", "ASIC", "CIRO", "MAS"],
    trustScore: 93,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Bonds"],
    accountTypes: ["Standard", "Premium", "Demo"],
    platforms: ["OANDA Web", "MT4", "TradingView", "Mobile App"],
    features: ["Research tools", "TradingView", "API", "Institutional history"],
    deposits: ["Card", "Bank transfer", "PayPal"],
    withdrawals: ["Bank transfer", "Card"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "Region based support hours",
    languages: "Multi-language support",
    supportEmail: "frontdesk@oanda.com",
    score: { regulation: 97, execution: 88, spreads: 84, withdrawals: 87, support: 88, platforms: 88, transparency: 94 },
    bestFor: "Regulation-first forex traders and researchers"
  }),
  broker("forex.com", {
    name: "FOREX.com",
    slug: "forex-com",
    logoFallback: "FX",
    founded: "2001",
    headquarters: "United States / StoneX Group",
    regulators: ["CFTC/NFA", "FCA", "CIRO", "ASIC", "MAS"],
    trustScore: 92,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Indices", "Commodities", "Shares", "Crypto CFDs"],
    accountTypes: ["Standard", "RAW Pricing", "MetaTrader", "Demo"],
    platforms: ["FOREX.com Web", "MT4", "MT5", "TradingView", "Mobile App"],
    features: ["Research", "TradingView", "Market analysis", "Education"],
    deposits: ["Card", "Bank transfer", "PayPal"],
    withdrawals: ["Bank transfer", "Card"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "Region based support hours",
    languages: "Multi-language support",
    supportEmail: "support@forex.com",
    score: { regulation: 96, execution: 88, spreads: 84, withdrawals: 86, support: 87, platforms: 90, transparency: 93 },
    bestFor: "US/regulated-market forex traders"
  }),
  broker("cmcmarkets.com", {
    name: "CMC Markets",
    slug: "cmc-markets",
    logoFallback: "CM",
    founded: "1989",
    headquarters: "London, United Kingdom",
    regulators: ["FCA", "ASIC", "CIRO", "MAS", "FMA"],
    trustScore: 93,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Indices", "Commodities", "Shares", "Treasuries", "Crypto CFDs"],
    accountTypes: ["CFD", "Spread Betting", "Professional", "Demo"],
    platforms: ["Next Generation", "MT4", "Mobile App"],
    features: ["Research", "Advanced platform", "Large instrument range"],
    deposits: ["Card", "Bank transfer"],
    withdrawals: ["Bank transfer", "Card"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "Region based support hours",
    languages: "Multi-language support",
    supportEmail: "clientmanagement@cmcmarkets.com",
    score: { regulation: 96, execution: 88, spreads: 86, withdrawals: 86, support: 88, platforms: 91, transparency: 93 },
    bestFor: "Regulated CFD traders who want a broad instrument universe"
  }),
  broker("ig.com", {
    name: "IG",
    slug: "ig",
    logoFallback: "IG",
    founded: "1974",
    headquarters: "London, United Kingdom",
    regulators: ["FCA", "ASIC", "CFTC/NFA", "MAS", "BaFin"],
    trustScore: 96,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Indices", "Commodities", "Shares", "Options", "Crypto CFDs"],
    accountTypes: ["CFD", "Spread Betting", "Professional", "Demo"],
    platforms: ["IG Platform", "MT4", "ProRealTime", "L2 Dealer", "Mobile App"],
    features: ["Research", "Education", "Advanced charting", "Large market coverage"],
    deposits: ["Card", "Bank transfer", "PayPal"],
    withdrawals: ["Bank transfer", "Card", "PayPal"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24-hour dealing/support by region",
    languages: "Multi-language support",
    supportEmail: "helpdesk@ig.com",
    score: { regulation: 98, execution: 90, spreads: 86, withdrawals: 88, support: 90, platforms: 94, transparency: 95 },
    bestFor: "Trust-focused traders who want a large, regulated broker"
  }),
  broker("xm.com", {
    name: "XM",
    slug: "xm",
    logoFallback: "XM",
    founded: "2009",
    headquarters: "Cyprus",
    regulators: ["CySEC", "ASIC", "FSC Belize", "DFSA"],
    trustScore: 84,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Shares"],
    accountTypes: ["Micro", "Standard", "Ultra Low", "Shares", "Demo"],
    platforms: ["MT4", "MT5", "Mobile App"],
    features: ["Education", "Bonuses by region", "EA support"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@xm.com",
    score: { regulation: 82, execution: 83, spreads: 82, withdrawals: 84, support: 86, platforms: 84, transparency: 82 },
    bestFor: "Beginner CFD traders who value education and account variety"
  }),
  broker("hfm.com", {
    name: "HFM",
    slug: "hfm",
    logoFallback: "HF",
    founded: "2010",
    headquarters: "Cyprus",
    regulators: ["FCA", "CySEC", "DFSA", "FSCA", "FSA Seychelles"],
    trustScore: 85,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Shares", "Crypto"],
    accountTypes: ["Cent", "Premium", "Zero", "Pro", "Demo"],
    platforms: ["MT4", "MT5", "Mobile App"],
    features: ["Copy trading", "Education", "EA support", "VPS"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller", "Crypto"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@hfm.com",
    score: { regulation: 85, execution: 84, spreads: 84, withdrawals: 84, support: 84, platforms: 84, transparency: 82 },
    bestFor: "Multi-account CFD traders in international markets"
  }),
  broker("avatrade.com", {
    name: "AvaTrade",
    slug: "avatrade",
    logoFallback: "AV",
    founded: "2006",
    headquarters: "Dublin, Ireland",
    regulators: ["Central Bank of Ireland", "ASIC", "FSCA", "FSA Japan", "ADGM"],
    trustScore: 87,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Commodities", "Indices", "Shares", "Options", "Crypto CFDs"],
    accountTypes: ["Retail", "Professional", "Islamic", "Demo"],
    platforms: ["AvaTradeGO", "MT4", "MT5", "AvaOptions", "WebTrader"],
    features: ["Options", "Copy trading", "Education", "Fixed spreads by region"],
    deposits: ["Card", "Bank transfer", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "cs@avatrade.com",
    score: { regulation: 89, execution: 82, spreads: 80, withdrawals: 83, support: 85, platforms: 87, transparency: 85 },
    bestFor: "Multi-asset traders who want broad platform choice"
  }),
  broker("xtb.com", {
    name: "XTB",
    slug: "xtb",
    logoFallback: "XT",
    founded: "2002",
    headquarters: "Warsaw, Poland",
    regulators: ["KNF", "FCA", "CySEC", "DFSA"],
    trustScore: 90,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Indices", "Commodities", "Shares", "ETFs", "Crypto CFDs"],
    accountTypes: ["Standard", "Professional", "Demo"],
    platforms: ["xStation", "Mobile App"],
    features: ["xStation", "Stocks/ETFs by region", "Education", "Research"],
    deposits: ["Card", "Bank transfer", "PayPal"],
    withdrawals: ["Bank transfer"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@xtb.com",
    score: { regulation: 92, execution: 86, spreads: 84, withdrawals: 86, support: 87, platforms: 88, transparency: 90 },
    bestFor: "xStation users and traders who want a listed European broker"
  }),
  broker("admiralmarkets.com", {
    name: "Admirals",
    slug: "admirals",
    logoFallback: "AD",
    founded: "2001",
    headquarters: "Tallinn, Estonia",
    regulators: ["FCA", "CySEC", "ASIC", "EFSA"],
    trustScore: 88,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Indices", "Commodities", "Shares", "ETFs", "Bonds"],
    accountTypes: ["Trade", "Zero", "Invest", "Demo"],
    platforms: ["MT4", "MT5", "WebTrader", "Mobile App"],
    features: ["MT5 Supreme Edition", "Invest account", "Education"],
    deposits: ["Card", "Bank transfer", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "global@admiralmarkets.com",
    score: { regulation: 90, execution: 85, spreads: 84, withdrawals: 84, support: 85, platforms: 88, transparency: 88 },
    bestFor: "MT4/MT5 traders who want CFDs plus investing tools"
  }),
  broker("swissquote.com", {
    name: "Swissquote",
    slug: "swissquote",
    logoFallback: "SQ",
    founded: "1996",
    headquarters: "Gland, Switzerland",
    regulators: ["FINMA", "FCA", "DFSA", "MAS"],
    trustScore: 94,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Stocks", "ETFs", "Funds", "Bonds", "Crypto"],
    accountTypes: ["Trading", "Forex", "Professional", "Demo"],
    platforms: ["Advanced Trader", "MT4", "MT5", "Mobile App"],
    features: ["Swiss bank", "Research", "Multi-asset investing"],
    deposits: ["Bank transfer", "Card"],
    withdrawals: ["Bank transfer"],
    support: ["Email", "Phone"],
    supportHours: "Banking/business hours by region",
    languages: "Multi-language support",
    supportEmail: "info@swissquote.com",
    score: { regulation: 98, execution: 86, spreads: 80, withdrawals: 86, support: 84, platforms: 86, transparency: 95 },
    bestFor: "Safety-first traders who want bank-grade infrastructure"
  }),
  broker("home.saxo", {
    name: "Saxo",
    slug: "saxo",
    logoFallback: "SX",
    founded: "1992",
    headquarters: "Copenhagen, Denmark",
    regulators: ["Danish FSA", "FCA", "FINMA", "ASIC", "MAS"],
    trustScore: 95,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Stocks", "ETFs", "Bonds", "Options", "Futures", "CFDs"],
    accountTypes: ["Classic", "Platinum", "VIP", "Professional"],
    platforms: ["SaxoTraderGO", "SaxoTraderPRO", "Mobile App"],
    features: ["Institutional platform", "Research", "Multi-asset coverage", "Options/futures"],
    deposits: ["Bank transfer", "Card by region"],
    withdrawals: ["Bank transfer"],
    support: ["Email", "Phone", "Help center"],
    supportHours: "Business hours by region",
    languages: "Multi-language support",
    supportEmail: "service@saxo.com",
    score: { regulation: 98, execution: 90, spreads: 82, withdrawals: 86, support: 86, platforms: 95, transparency: 94 },
    bestFor: "Serious multi-asset traders and investors"
  }),
  broker("axi.com", {
    name: "Axi",
    slug: "axi",
    logoFallback: "AX",
    founded: "2007",
    headquarters: "Sydney, Australia",
    regulators: ["ASIC", "FCA", "DFSA", "FMA"],
    trustScore: 88,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Crypto CFDs"],
    accountTypes: ["Standard", "Pro", "Elite", "Demo"],
    platforms: ["MT4", "Mobile App"],
    features: ["Copy trading", "EA support", "VPS", "MT4 specialist"],
    deposits: ["Card", "Bank transfer", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "service@axi.com",
    score: { regulation: 90, execution: 86, spreads: 86, withdrawals: 84, support: 85, platforms: 82, transparency: 86 },
    bestFor: "MT4-focused forex and index traders"
  }),
  broker("fxtm.com", {
    name: "FXTM",
    slug: "fxtm",
    logoFallback: "FT",
    founded: "2011",
    headquarters: "Limassol, Cyprus",
    regulators: ["FCA", "CySEC", "FSCA", "FSC Mauritius"],
    trustScore: 84,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Stocks"],
    accountTypes: ["Advantage", "Advantage Plus", "Demo"],
    platforms: ["MT4", "MT5", "Mobile App"],
    features: ["Education", "Copy trading by region", "EA support"],
    deposits: ["Card", "Bank transfer", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@fxtm.com",
    score: { regulation: 85, execution: 83, spreads: 82, withdrawals: 82, support: 84, platforms: 84, transparency: 82 },
    bestFor: "Education-led forex traders in supported regions"
  }),
  broker("fxpro.com", {
    name: "FxPro",
    slug: "fxpro",
    logoFallback: "FP",
    founded: "2006",
    headquarters: "London, United Kingdom",
    regulators: ["FCA", "CySEC", "FSCA", "SCB"],
    trustScore: 89,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Energies", "Shares", "Crypto CFDs"],
    accountTypes: ["Standard", "Raw+", "Elite", "Demo"],
    platforms: ["MT4", "MT5", "cTrader", "FxPro Platform"],
    features: ["cTrader", "EA support", "Scalping", "VPS"],
    deposits: ["Card", "Bank transfer", "PayPal", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@fxpro.com",
    score: { regulation: 91, execution: 88, spreads: 86, withdrawals: 86, support: 86, platforms: 91, transparency: 88 },
    bestFor: "Traders who want MT4, MT5 and cTrader under one broker"
  }),
  broker("blackbull.com", {
    name: "BlackBull Markets",
    slug: "blackbull-markets",
    logoFallback: "BB",
    founded: "2014",
    headquarters: "Auckland, New Zealand",
    regulators: ["FMA New Zealand", "FSA Seychelles"],
    trustScore: 86,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Shares", "Crypto CFDs"],
    accountTypes: ["ECN Standard", "ECN Prime", "ECN Institutional", "Demo"],
    platforms: ["MT4", "MT5", "TradingView", "cTrader"],
    features: ["ECN accounts", "TradingView", "Copy trading", "VPS"],
    deposits: ["Card", "Bank transfer", "Skrill", "Neteller"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@blackbull.com",
    score: { regulation: 84, execution: 88, spreads: 88, withdrawals: 84, support: 86, platforms: 93, transparency: 84 },
    bestFor: "TradingView and ECN-style traders"
  }),
  broker("thinkmarkets.com", {
    name: "ThinkMarkets",
    slug: "thinkmarkets",
    logoFallback: "TH",
    founded: "2010",
    headquarters: "London, United Kingdom",
    regulators: ["FCA", "ASIC", "CySEC", "FSA Seychelles", "FSCA"],
    trustScore: 88,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Indices", "Metals", "Commodities", "Shares", "Crypto CFDs"],
    accountTypes: ["Standard", "ThinkZero", "Islamic", "Demo"],
    platforms: ["ThinkTrader", "MT4", "MT5"],
    features: ["ThinkTrader", "EA support", "Education", "Trading tools"],
    deposits: ["Card", "Bank transfer", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@thinkmarkets.com",
    score: { regulation: 90, execution: 86, spreads: 85, withdrawals: 84, support: 85, platforms: 88, transparency: 86 },
    bestFor: "Traders who want proprietary apps plus MetaTrader"
  }),
  broker("deriv.com", {
    name: "Deriv",
    slug: "deriv",
    logoFallback: "DV",
    founded: "1999",
    headquarters: "Multi-jurisdiction",
    regulators: ["MFSA", "Labuan FSA", "VFSC", "BVI FSC"],
    trustScore: 82,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Synthetic indices", "Commodities", "Stocks", "Crypto"],
    accountTypes: ["CFD", "Derived", "Financial", "Demo"],
    platforms: ["Deriv Trader", "Deriv X", "MT5", "cTrader", "Bot"],
    features: ["Synthetic indices", "Bot trading", "24/7 markets", "MT5"],
    deposits: ["Card", "Bank transfer", "Crypto", "E-wallets"],
    withdrawals: ["Bank transfer", "Crypto", "E-wallets"],
    support: ["Live chat", "Help center", "Community"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@deriv.com",
    score: { regulation: 78, execution: 84, spreads: 82, withdrawals: 82, support: 82, platforms: 90, transparency: 80 },
    bestFor: "Synthetic-index traders and 24/7 market access"
  }),
  broker("fbs.com", {
    name: "FBS",
    slug: "fbs",
    logoFallback: "FB",
    founded: "2009",
    headquarters: "Belize / Cyprus entities",
    regulators: ["CySEC", "FSC Belize", "ASIC entity"],
    trustScore: 81,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Energies", "Stocks", "Crypto"],
    accountTypes: ["Standard", "Cent", "Pro", "Demo"],
    platforms: ["MT4", "MT5", "FBS App"],
    features: ["Education", "Promotions by region", "Copy/social tools by region"],
    deposits: ["Card", "Bank transfer", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@fbs.com",
    score: { regulation: 78, execution: 80, spreads: 80, withdrawals: 80, support: 83, platforms: 82, transparency: 78 },
    bestFor: "Beginner traders in supported international markets"
  }),
  broker("tradenation.com", {
    name: "Trade Nation",
    slug: "trade-nation",
    logoFallback: "TN",
    founded: "2014",
    headquarters: "London, United Kingdom",
    regulators: ["FCA", "ASIC", "FSCA", "SCB"],
    trustScore: 86,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Indices", "Commodities", "Shares", "Bonds"],
    accountTypes: ["Retail", "Professional", "Demo"],
    platforms: ["Trade Nation Platform", "TradingView", "MT4"],
    features: ["Fixed spread model by market", "TradingView", "Education"],
    deposits: ["Card", "Bank transfer"],
    withdrawals: ["Bank transfer", "Card"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "English support baseline",
    supportEmail: "support@tradenation.com",
    score: { regulation: 90, execution: 84, spreads: 82, withdrawals: 84, support: 84, platforms: 86, transparency: 86 },
    bestFor: "Traders who prefer simple pricing and regulated entities"
  }),
  broker("plus500.com", {
    name: "Plus500",
    slug: "plus500",
    logoFallback: "P5",
    founded: "2008",
    headquarters: "Israel / London-listed group",
    regulators: ["FCA", "ASIC", "CySEC", "MAS", "FMA"],
    trustScore: 90,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Indices", "Commodities", "Shares", "Options", "Crypto CFDs"],
    accountTypes: ["Retail CFD", "Professional", "Demo"],
    platforms: ["Plus500 WebTrader", "Mobile App"],
    features: ["Simple platform", "Risk controls", "Large CFD list"],
    deposits: ["Card", "Bank transfer", "PayPal", "Skrill"],
    withdrawals: ["Bank transfer", "Card", "PayPal", "Skrill"],
    support: ["Live chat", "Email"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@plus500.com",
    score: { regulation: 94, execution: 84, spreads: 80, withdrawals: 86, support: 84, platforms: 80, transparency: 88 },
    bestFor: "Simple CFD trading with strong public-company/regulatory footprint"
  }),
  broker("interactivebrokers.com", {
    name: "Interactive Brokers",
    slug: "interactive-brokers",
    logoFallback: "IB",
    founded: "1978",
    headquarters: "Greenwich, United States",
    regulators: ["SEC/FINRA", "CFTC/NFA", "FCA", "ASIC", "MAS"],
    trustScore: 97,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Stocks", "Options", "Futures", "Forex", "Bonds", "Funds", "Crypto by region"],
    accountTypes: ["Individual", "Professional", "Institutional", "Demo"],
    platforms: ["Trader Workstation", "IBKR Desktop", "Client Portal", "Mobile App"],
    features: ["Professional platform", "Global markets", "API", "Institutional-grade execution"],
    deposits: ["Bank transfer", "ACH by region"],
    withdrawals: ["Bank transfer", "ACH by region"],
    support: ["Ticket", "Phone", "Chat by region"],
    supportHours: "Region based support hours",
    languages: "Multi-language support",
    supportEmail: "help@interactivebrokers.com",
    score: { regulation: 99, execution: 94, spreads: 86, withdrawals: 88, support: 84, platforms: 96, transparency: 96 },
    bestFor: "Advanced traders who need global market access and professional tools"
  }),
  broker("justmarkets.com", {
    name: "JustMarkets",
    slug: "justmarkets",
    logoFallback: "JM",
    founded: "2012",
    headquarters: "Multi-jurisdiction",
    regulators: ["CySEC entity", "FSA Seychelles", "FSCA entity"],
    trustScore: 80,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Stocks", "Crypto"],
    accountTypes: ["Standard", "Pro", "Raw Spread", "Cent", "Demo"],
    platforms: ["MT4", "MT5", "Mobile App"],
    features: ["Copy trading by region", "EA support", "Scalping", "Swap-free by region"],
    deposits: ["Card", "Bank transfer", "Crypto", "E-wallets", "Local methods by region"],
    withdrawals: ["Bank transfer", "Card", "Crypto", "E-wallets"],
    support: ["Live chat", "Email", "Help center"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@justmarkets.com",
    score: { regulation: 78, execution: 82, spreads: 84, withdrawals: 82, support: 84, platforms: 84, transparency: 78 },
    bestFor: "International traders who want low-deposit account options and MetaTrader access"
  }),
  broker("roboforex.com", {
    name: "RoboForex",
    slug: "roboforex",
    logoFallback: "RF",
    founded: "2009",
    headquarters: "Belize / international entities",
    regulators: ["FSC Belize"],
    trustScore: 78,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Stocks", "ETFs", "Crypto"],
    accountTypes: ["Pro", "Prime", "ECN", "ProCent", "R StocksTrader", "Demo"],
    platforms: ["MT4", "MT5", "R StocksTrader", "Mobile App"],
    features: ["CopyFX", "Cent accounts", "EA support", "Stocks platform"],
    deposits: ["Card", "Bank transfer", "E-wallets", "Crypto by region"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Help center"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "info@roboforex.com",
    score: { regulation: 70, execution: 82, spreads: 82, withdrawals: 80, support: 82, platforms: 88, transparency: 76 },
    bestFor: "Traders comparing cent accounts, MetaTrader and stock-CFD style platforms"
  }),
  broker("litefinance.org", {
    name: "LiteFinance",
    slug: "litefinance",
    logoFallback: "LF",
    founded: "2005",
    headquarters: "Multi-jurisdiction",
    regulators: ["CySEC entity", "International entity"],
    trustScore: 79,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Oil", "Indices", "Stocks", "Crypto"],
    accountTypes: ["Classic", "ECN", "Cent", "Demo"],
    platforms: ["MT4", "MT5", "Web platform", "Mobile App"],
    features: ["Copy trading", "Social trading", "EA support", "Education"],
    deposits: ["Card", "Bank transfer", "Crypto", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "Crypto", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "clients@litefinance.com",
    score: { regulation: 76, execution: 80, spreads: 80, withdrawals: 80, support: 80, platforms: 84, transparency: 78 },
    bestFor: "Copy-trading and MetaTrader users researching international CFD brokers"
  }),
  broker("fxcm.com", {
    name: "FXCM",
    slug: "fxcm",
    logoFallback: "FC",
    founded: "1999",
    headquarters: "London, United Kingdom",
    regulators: ["FCA", "ASIC", "FSCA", "CySEC entity"],
    trustScore: 87,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Indices", "Commodities", "Shares", "Crypto baskets by region"],
    accountTypes: ["Standard", "Active Trader", "Professional", "Demo"],
    platforms: ["Trading Station", "MT4", "TradingView", "ZuluTrade"],
    features: ["TradingView", "API", "Copy trading integrations", "Education"],
    deposits: ["Card", "Bank transfer", "E-wallets by region"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "info@fxcm.com",
    score: { regulation: 90, execution: 86, spreads: 82, withdrawals: 84, support: 84, platforms: 90, transparency: 86 },
    bestFor: "Traders who want TradingView, API access and a long-established CFD broker"
  }),
  broker("capital.com", {
    name: "Capital.com",
    slug: "capital-com",
    logoFallback: "CC",
    founded: "2016",
    headquarters: "London / global entities",
    regulators: ["FCA", "CySEC", "ASIC", "SCB"],
    trustScore: 88,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Indices", "Commodities", "Shares", "ETFs", "Crypto CFDs by region"],
    accountTypes: ["Retail CFD", "Professional", "Demo"],
    platforms: ["Capital.com Web", "Mobile App", "TradingView", "MT4 by region"],
    features: ["TradingView", "Education", "Risk controls", "Large CFD list"],
    deposits: ["Card", "Bank transfer", "Apple Pay", "Google Pay", "E-wallets by region"],
    withdrawals: ["Bank transfer", "Card", "E-wallets by region"],
    support: ["Live chat", "Email", "Help center"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@capital.com",
    score: { regulation: 91, execution: 86, spreads: 84, withdrawals: 84, support: 86, platforms: 88, transparency: 88 },
    bestFor: "Traders who want a modern CFD platform with TradingView support"
  }),
  broker("etoro.com", {
    name: "eToro",
    slug: "etoro",
    logoFallback: "ET",
    founded: "2007",
    headquarters: "Israel / global entities",
    regulators: ["FCA", "CySEC", "ASIC", "SEC/FINRA entity"],
    trustScore: 89,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Stocks", "ETFs", "Crypto", "Forex", "Commodities", "Indices"],
    accountTypes: ["Retail", "Professional", "Demo"],
    platforms: ["eToro Web", "Mobile App"],
    features: ["CopyTrader", "Social investing", "Smart Portfolios", "Stocks by region"],
    deposits: ["Card", "Bank transfer", "PayPal by region", "E-wallets by region"],
    withdrawals: ["Bank transfer", "Card", "E-wallets by region"],
    support: ["Help center", "Ticket", "Chat by region"],
    supportHours: "Region based support hours",
    languages: "Multi-language support",
    supportEmail: "support@etoro.com",
    score: { regulation: 92, execution: 82, spreads: 78, withdrawals: 82, support: 78, platforms: 84, transparency: 86 },
    bestFor: "Social investing and copy-trading users who want a simple multi-asset platform"
  }),
  broker("tmgm.com", {
    name: "TMGM",
    slug: "tmgm",
    logoFallback: "TG",
    founded: "2013",
    headquarters: "Sydney, Australia",
    regulators: ["ASIC", "VFSC", "FMA entity"],
    trustScore: 84,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Shares", "Crypto"],
    accountTypes: ["Classic", "Edge", "Demo"],
    platforms: ["MT4", "MT5", "TradingView", "Hub platform"],
    features: ["TradingView", "EA support", "Scalping", "Education"],
    deposits: ["Card", "Bank transfer", "E-wallets", "Local methods by region"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@tmgm.com",
    score: { regulation: 84, execution: 86, spreads: 85, withdrawals: 82, support: 82, platforms: 88, transparency: 82 },
    bestFor: "CFD traders comparing MT4, MT5 and TradingView broker access"
  }),
  broker("vtmarkets.com", {
    name: "VT Markets",
    slug: "vt-markets",
    logoFallback: "VT",
    founded: "2015",
    headquarters: "Sydney / international entities",
    regulators: ["ASIC entity", "FSCA entity", "FSC Mauritius"],
    trustScore: 82,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Shares", "Crypto"],
    accountTypes: ["Standard STP", "Raw ECN", "Cent", "Demo"],
    platforms: ["MT4", "MT5", "WebTrader", "Mobile App"],
    features: ["Copy trading", "EA support", "Promotions by region", "VPS by region"],
    deposits: ["Card", "Bank transfer", "E-wallets", "Crypto by region"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "info@vtmarkets.com",
    score: { regulation: 80, execution: 84, spreads: 84, withdrawals: 82, support: 82, platforms: 84, transparency: 80 },
    bestFor: "International CFD traders comparing Raw ECN and standard MetaTrader accounts"
  }),
  broker("puprime.com", {
    name: "PU Prime",
    slug: "pu-prime",
    logoFallback: "PU",
    founded: "2015",
    headquarters: "Multi-jurisdiction",
    regulators: ["FSA Seychelles", "FSCA entity", "ASIC entity"],
    trustScore: 80,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Shares", "Crypto"],
    accountTypes: ["Standard", "Prime", "Cent", "Demo"],
    platforms: ["MT4", "MT5", "Mobile App"],
    features: ["Copy trading", "Promotions by region", "EA support", "Education"],
    deposits: ["Card", "Bank transfer", "Crypto", "E-wallets", "Local methods by region"],
    withdrawals: ["Bank transfer", "Card", "Crypto", "E-wallets"],
    support: ["Live chat", "Email"],
    supportHours: "24/5 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@puprime.com",
    score: { regulation: 78, execution: 82, spreads: 82, withdrawals: 80, support: 82, platforms: 82, transparency: 78 },
    bestFor: "International traders researching low-entry CFD accounts and MetaTrader"
  }),
  broker("multibankfx.com", {
    name: "MultiBank Group",
    slug: "multibank-group",
    logoFallback: "MB",
    founded: "2005",
    headquarters: "Dubai / global entities",
    regulators: ["ASIC", "BaFin", "CySEC", "DFSA", "FSC entities"],
    trustScore: 86,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Shares", "Crypto"],
    accountTypes: ["Standard", "Pro", "ECN", "Demo"],
    platforms: ["MT4", "MT5", "Mobile App"],
    features: ["Multi-regulated group", "EA support", "Scalping", "Copy tools by region"],
    deposits: ["Card", "Bank transfer", "Crypto", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "Crypto", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/7 support advertised by broker",
    languages: "Multi-language support",
    supportEmail: "support@multibankfx.com",
    score: { regulation: 88, execution: 84, spreads: 84, withdrawals: 84, support: 84, platforms: 84, transparency: 84 },
    bestFor: "Traders comparing multi-regulated CFD brokers with global entity choice"
  }),
  broker("blueberrymarkets.com", {
    name: "Blueberry Markets",
    slug: "blueberry-markets",
    logoFallback: "BB",
    founded: "2016",
    headquarters: "Sydney, Australia",
    regulators: ["ASIC entity", "VFSC entity"],
    trustScore: 83,
    verifiedStatus: "Source-reviewed",
    lastVerified: "Editorial review in progress",
    markets: ["Forex", "Metals", "Indices", "Commodities", "Crypto"],
    accountTypes: ["Standard", "Direct", "Demo"],
    platforms: ["MT4", "MT5", "WebTrader"],
    features: ["EA support", "Scalping", "Education", "Copy tools by platform"],
    deposits: ["Card", "Bank transfer", "E-wallets"],
    withdrawals: ["Bank transfer", "Card", "E-wallets"],
    support: ["Live chat", "Email", "Phone"],
    supportHours: "24/5 support advertised by broker",
    languages: "English support baseline",
    supportEmail: "support@blueberrymarkets.com",
    score: { regulation: 82, execution: 84, spreads: 84, withdrawals: 82, support: 86, platforms: 82, transparency: 82 },
    bestFor: "MetaTrader traders who value support reputation and simple account types"
  })
];

export const brokerScoreWeights = [
  ["Withdrawal reliability", 20],
  ["Rule transparency", 15],
  ["Customer support", 15],
  ["Trading conditions", 20],
  ["Platform stability", 15],
  ["Community trust", 15]
] as const;

function average(values: number[]) {
  return values.reduce((total, value) => total + value, 0) / values.length;
}

export function getBrokerConfidenceBreakdown(brokerItem: Broker): BrokerConfidenceBreakdown {
  const baseRows = [
    {
      key: "withdrawals",
      label: "Withdrawal reliability",
      value: brokerItem.score.withdrawals,
      max: 20,
      explanation: "Withdrawal methods, payment flexibility and reliability indicators."
    },
    {
      key: "transparency",
      label: "Rule transparency",
      value: brokerItem.score.transparency,
      max: 15,
      explanation: "How clearly the broker explains accounts, fees, platforms and important trading conditions."
    },
    {
      key: "support",
      label: "Customer support",
      value: brokerItem.score.support,
      max: 15,
      explanation: "Support channels, advertised hours, languages and access to help when account issues happen."
    },
    {
      key: "conditions",
      label: "Trading conditions",
      value: Math.round(average([brokerItem.score.execution, brokerItem.score.spreads])),
      max: 20,
      explanation: "Execution, spread transparency, account types, instrument coverage and trading-cost signals."
    },
    {
      key: "platforms",
      label: "Platform stability",
      value: brokerItem.score.platforms,
      max: 15,
      explanation: "Supported platforms, platform breadth and trading-tool availability."
    },
    {
      key: "community",
      label: "Community trust",
      value: Math.round(average([brokerItem.score.regulation, brokerItem.score.transparency])),
      max: 15,
      explanation: "Regulatory footprint, transparency and reputation signals available for review."
    }
  ];

  const rows = baseRows.map((row) => ({
    ...row,
    value: Math.round((row.value / 100) * row.max)
  }));
  const rawTotal = rows.reduce((total, row) => total + row.value, 0);
  let correction = brokerItem.trustScore - rawTotal;
  const sortedRows = [...rows].sort((a, b) => b.max - a.max);
  while (correction !== 0) {
    const row = correction > 0 ? sortedRows.find((item) => item.value < item.max) : sortedRows.find((item) => item.value > 0);
    if (!row) break;
    row.value += correction > 0 ? 1 : -1;
    correction += correction > 0 ? -1 : 1;
  }

  return {
    total: brokerItem.trustScore,
    max: 100,
    label: "FundedScope Confidence Score™",
    formula:
      "Broker confidence is calculated from withdrawal reliability, rule transparency, customer support, trading conditions, platform stability and community trust. Paid placements cannot buy a higher score.",
    rows,
    lastReviewed: brokerItem.lastVerified,
    dataWarning:
      brokerItem.verifiedStatus === "Verified profile"
        ? "Baseline broker information has been verified by FundedScope."
        : "This broker is in our research queue. Core profile details are shown, but exact live spreads and time-sensitive claims stay hidden until official-feed or manual verification is complete."
  };
}

export const brokerStats = {
  brokers: brokers.length,
  regulators: new Set(brokers.flatMap((brokerItem) => brokerItem.regulators)).size,
  instruments: new Set(brokers.flatMap((brokerItem) => brokerItem.instruments.map((instrument) => instrument.symbol))).size,
  platforms: new Set(brokers.flatMap((brokerItem) => brokerItem.platforms)).size
};
