import { brokers } from "./brokers";

const favicon = (domain: string) => `https://logo.clearbit.com/${domain}`;

export type PropFirm = {
  name: string;
  slug: string;
  domain: string;
  logoUrl: string;
  logoFallback: string;
  accent: string;
  score: number;
  rating: number;
  reviewCount: number;
  payout: string;
  payoutFrequency: string;
  maxDrawdown: string;
  dailyDrawdown: string;
  profitTarget: string;
  challengeFee: string;
  maxAccount: string;
  country: string;
  markets: string[];
  challengeTypes: string[];
  tags: string[];
  verified: boolean;
  lastRuleUpdate: string;
  summary: string;
};

export const propFirms: PropFirm[] = [
  {
    name: "FTMO",
    slug: "ftmo",
    domain: "ftmo.com",
    logoUrl: favicon("ftmo.com"),
    logoFallback: "FT",
    accent: "from-cyan-400 to-blue-600",
    score: 94,
    rating: 4.8,
    reviewCount: 18420,
    payout: "Bi-weekly",
    payoutFrequency: "Bi-weekly",
    maxDrawdown: "10%",
    dailyDrawdown: "5%",
    profitTarget: "10% / 5%",
    challengeFee: "$199",
    maxAccount: "$400k",
    country: "Czech Republic",
    markets: ["Forex", "Indices", "Commodities", "Crypto"],
    challengeTypes: ["Two-step"],
    tags: ["Established", "Strict rules", "Scaling"],
    verified: true,
    lastRuleUpdate: "2026-06-18",
    summary: "One of the most established evaluation firms with strong brand trust and mature trader infrastructure."
  },
  {
    name: "The5ers",
    slug: "the5ers",
    domain: "the5ers.com",
    logoUrl: favicon("the5ers.com"),
    logoFallback: "5R",
    accent: "from-emerald-400 to-cyan-500",
    score: 91,
    rating: 4.7,
    reviewCount: 9320,
    payout: "On demand",
    payoutFrequency: "On demand",
    maxDrawdown: "6%",
    dailyDrawdown: "3%",
    profitTarget: "6% / 6%",
    challengeFee: "$49",
    maxAccount: "$4M scaling",
    country: "Israel",
    markets: ["Forex", "Indices", "Commodities"],
    challengeTypes: ["One-step", "Two-step", "Instant funding"],
    tags: ["Low risk", "Scaling", "Swing"],
    verified: true,
    lastRuleUpdate: "2026-05-29",
    summary: "Strong fit for patient traders who care about scaling plans and lower-risk evaluation structures."
  },
  {
    name: "FundedNext",
    slug: "fundednext",
    domain: "fundednext.com",
    logoUrl: favicon("fundednext.com"),
    logoFallback: "FN",
    accent: "from-violet-500 to-fuchsia-500",
    score: 89,
    rating: 4.6,
    reviewCount: 15400,
    payout: "14 days",
    payoutFrequency: "14 days",
    maxDrawdown: "10%",
    dailyDrawdown: "5%",
    profitTarget: "8% / 5%",
    challengeFee: "$79",
    maxAccount: "$300k",
    country: "UAE",
    markets: ["Forex", "Indices", "Commodities", "Crypto"],
    challengeTypes: ["One-step", "Two-step"],
    tags: ["Fast payouts", "Multi-step", "Crypto"],
    verified: true,
    lastRuleUpdate: "2026-06-11",
    summary: "A popular global firm with broad market coverage, frequent promotions and a strong trader acquisition engine."
  },
  {
    name: "Funding Pips",
    slug: "funding-pips",
    domain: "fundingpips.com",
    logoUrl: favicon("fundingpips.com"),
    logoFallback: "FP",
    accent: "from-sky-400 to-indigo-500",
    score: 88,
    rating: 4.6,
    reviewCount: 7800,
    payout: "5 days",
    payoutFrequency: "5 days",
    maxDrawdown: "10%",
    dailyDrawdown: "5%",
    profitTarget: "8% / 5%",
    challengeFee: "$39",
    maxAccount: "$300k",
    country: "UAE",
    markets: ["Forex", "Indices", "Commodities", "Crypto"],
    challengeTypes: ["One-step", "Two-step"],
    tags: ["Fast growth", "Low entry", "Promos"],
    verified: true,
    lastRuleUpdate: "2026-06-20",
    summary: "Fast-growing evaluation firm known for competitive pricing and frequent trader-facing campaigns."
  },
  {
    name: "Alpha Capital Group",
    slug: "alpha-capital-group",
    domain: "alphacapitalgroup.uk",
    logoUrl: favicon("alphacapitalgroup.uk"),
    logoFallback: "AC",
    accent: "from-blue-500 to-purple-600",
    score: 87,
    rating: 4.5,
    reviewCount: 6900,
    payout: "Bi-weekly",
    payoutFrequency: "Bi-weekly",
    maxDrawdown: "10%",
    dailyDrawdown: "5%",
    profitTarget: "8% / 5%",
    challengeFee: "$129",
    maxAccount: "$200k",
    country: "United Kingdom",
    markets: ["Forex", "Indices", "Commodities"],
    challengeTypes: ["Two-step"],
    tags: ["UK", "Professional", "FX"],
    verified: true,
    lastRuleUpdate: "2026-05-26",
    summary: "UK-based firm positioned toward disciplined FX and CFD traders who want a polished evaluation experience."
  },
  {
    name: "E8 Markets",
    slug: "e8-markets",
    domain: "e8markets.com",
    logoUrl: favicon("e8markets.com"),
    logoFallback: "E8",
    accent: "from-indigo-400 to-cyan-400",
    score: 86,
    rating: 4.5,
    reviewCount: 6200,
    payout: "8 days",
    payoutFrequency: "8 days",
    maxDrawdown: "8%",
    dailyDrawdown: "4%",
    profitTarget: "8% / 5%",
    challengeFee: "$179",
    maxAccount: "$400k",
    country: "United States",
    markets: ["Forex", "Indices", "Commodities", "Crypto"],
    challengeTypes: ["One-step", "Two-step"],
    tags: ["Analytics", "Modern UI", "Scaling"],
    verified: true,
    lastRuleUpdate: "2026-06-03",
    summary: "Modern evaluation firm with a strong dashboard feel and broad challenge variations."
  },
  {
    name: "Topstep",
    slug: "topstep",
    domain: "topstep.com",
    logoUrl: favicon("topstep.com"),
    logoFallback: "TS",
    accent: "from-orange-400 to-red-500",
    score: 90,
    rating: 4.6,
    reviewCount: 12100,
    payout: "Weekly",
    payoutFrequency: "Weekly",
    maxDrawdown: "Trailing",
    dailyDrawdown: "Plan based",
    profitTarget: "Futures target",
    challengeFee: "$59",
    maxAccount: "$189k",
    country: "United States",
    markets: ["Futures"],
    challengeTypes: ["Futures combine"],
    tags: ["Futures", "Established", "Education"],
    verified: true,
    lastRuleUpdate: "2026-06-14",
    summary: "A leading futures funding brand with a long operating history and trader education footprint."
  },
  {
    name: "Apex Trader Funding",
    slug: "apex-trader-funding",
    domain: "apextraderfunding.com",
    logoUrl: favicon("apextraderfunding.com"),
    logoFallback: "AP",
    accent: "from-yellow-400 to-orange-500",
    score: 85,
    rating: 4.4,
    reviewCount: 9800,
    payout: "2x monthly",
    payoutFrequency: "2x monthly",
    maxDrawdown: "Trailing",
    dailyDrawdown: "None",
    profitTarget: "Futures target",
    challengeFee: "$169",
    maxAccount: "$300k",
    country: "United States",
    markets: ["Futures"],
    challengeTypes: ["Futures evaluation"],
    tags: ["Futures", "Large promos", "Multiple accounts"],
    verified: true,
    lastRuleUpdate: "2026-06-08",
    summary: "High-volume futures funding firm known for aggressive discounts and multi-account traders."
  },
  {
    name: "MyFundedFutures",
    slug: "myfundedfutures",
    domain: "myfundedfutures.com",
    logoUrl: favicon("myfundedfutures.com"),
    logoFallback: "MF",
    accent: "from-cyan-300 to-violet-500",
    score: 84,
    rating: 4.4,
    reviewCount: 3900,
    payout: "Weekly",
    payoutFrequency: "Weekly",
    maxDrawdown: "Trailing/EOD",
    dailyDrawdown: "Plan based",
    profitTarget: "Futures target",
    challengeFee: "$99",
    maxAccount: "$189k",
    country: "United States",
    markets: ["Futures"],
    challengeTypes: ["Futures evaluation"],
    tags: ["Futures", "Simple plans", "Weekly payouts"],
    verified: true,
    lastRuleUpdate: "2026-05-31",
    summary: "Futures-focused prop firm with trader-friendly account options and simple plan positioning."
  },
  {
    name: "Take Profit Trader",
    slug: "take-profit-trader",
    domain: "takeprofittrader.com",
    logoUrl: favicon("takeprofittrader.com"),
    logoFallback: "TP",
    accent: "from-green-400 to-lime-500",
    score: 83,
    rating: 4.4,
    reviewCount: 4100,
    payout: "Fast payout",
    payoutFrequency: "Fast payout",
    maxDrawdown: "Trailing",
    dailyDrawdown: "Plan based",
    profitTarget: "Futures target",
    challengeFee: "$189",
    maxAccount: "$189k",
    country: "United States",
    markets: ["Futures"],
    challengeTypes: ["Futures evaluation"],
    tags: ["Futures", "Payout speed", "Simple rules"],
    verified: true,
    lastRuleUpdate: "2026-06-01",
    summary: "Futures prop option focused on direct payout positioning and simpler trader messaging."
  },
  {
    name: "Earn2Trade",
    slug: "earn2trade",
    domain: "earn2trade.com",
    logoUrl: favicon("earn2trade.com"),
    logoFallback: "E2",
    accent: "from-blue-400 to-cyan-500",
    score: 82,
    rating: 4.3,
    reviewCount: 5200,
    payout: "Monthly",
    payoutFrequency: "Monthly",
    maxDrawdown: "Plan based",
    dailyDrawdown: "Plan based",
    profitTarget: "Futures target",
    challengeFee: "$189",
    maxAccount: "$200k",
    country: "United States",
    markets: ["Futures"],
    challengeTypes: ["Futures evaluation"],
    tags: ["Education", "Futures", "Gauntlet"],
    verified: true,
    lastRuleUpdate: "2026-05-20",
    summary: "Education-led futures evaluation company with structured paths for developing traders."
  },
  {
    name: "Funded Trading Plus",
    slug: "funded-trading-plus",
    domain: "fundedtradingplus.com",
    logoUrl: favicon("fundedtradingplus.com"),
    logoFallback: "FT+",
    accent: "from-emerald-400 to-blue-500",
    score: 84,
    rating: 4.4,
    reviewCount: 4700,
    payout: "On demand",
    payoutFrequency: "On demand",
    maxDrawdown: "6%",
    dailyDrawdown: "None/specific",
    profitTarget: "10%",
    challengeFee: "$149",
    maxAccount: "$200k",
    country: "United Kingdom",
    markets: ["Forex", "Indices", "Commodities"],
    challengeTypes: ["One-step", "Two-step", "Instant funding"],
    tags: ["UK", "Instant", "No daily DD options"],
    verified: true,
    lastRuleUpdate: "2026-05-19",
    summary: "UK firm with varied account structures, including instant and evaluation-style products."
  },
  {
    name: "Audacity Capital",
    slug: "audacity-capital",
    domain: "audacitycapital.co.uk",
    logoUrl: favicon("audacitycapital.co.uk"),
    logoFallback: "AU",
    accent: "from-red-400 to-fuchsia-500",
    score: 81,
    rating: 4.2,
    reviewCount: 3600,
    payout: "Monthly",
    payoutFrequency: "Monthly",
    maxDrawdown: "10%",
    dailyDrawdown: "Plan based",
    profitTarget: "10%",
    challengeFee: "$159",
    maxAccount: "$500k scaling",
    country: "United Kingdom",
    markets: ["Forex", "Indices", "Commodities"],
    challengeTypes: ["Evaluation", "Funded trader"],
    tags: ["UK", "Scaling", "Established"],
    verified: true,
    lastRuleUpdate: "2026-04-30",
    summary: "Established UK prop firm with evaluation and funded trader program structures."
  },
  {
    name: "Blue Guardian",
    slug: "blue-guardian",
    domain: "blueguardian.com",
    logoUrl: favicon("blueguardian.com"),
    logoFallback: "BG",
    accent: "from-blue-500 to-sky-300",
    score: 80,
    rating: 4.2,
    reviewCount: 4300,
    payout: "Bi-weekly",
    payoutFrequency: "Bi-weekly",
    maxDrawdown: "10%",
    dailyDrawdown: "4%",
    profitTarget: "8% / 4%",
    challengeFee: "$109",
    maxAccount: "$200k",
    country: "United Kingdom",
    markets: ["Forex", "Indices", "Commodities"],
    challengeTypes: ["One-step", "Two-step"],
    tags: ["FX", "Discounts", "Multi-plan"],
    verified: true,
    lastRuleUpdate: "2026-06-05",
    summary: "Multi-plan CFD prop firm with strong retail awareness and frequent offer cycles."
  },
  {
    name: "Goat Funded Trader",
    slug: "goat-funded-trader",
    domain: "goatfundedtrader.com",
    logoUrl: favicon("goatfundedtrader.com"),
    logoFallback: "GT",
    accent: "from-zinc-200 to-yellow-400",
    score: 79,
    rating: 4.2,
    reviewCount: 5100,
    payout: "Bi-weekly",
    payoutFrequency: "Bi-weekly",
    maxDrawdown: "10%",
    dailyDrawdown: "5%",
    profitTarget: "8% / 5%",
    challengeFee: "$89",
    maxAccount: "$200k",
    country: "UAE",
    markets: ["Forex", "Indices", "Crypto", "Commodities"],
    challengeTypes: ["One-step", "Two-step"],
    tags: ["Promos", "Crypto", "Retail popular"],
    verified: true,
    lastRuleUpdate: "2026-06-09",
    summary: "Retail-popular CFD prop firm with aggressive marketing and broad challenge accessibility."
  },
  {
    name: "FXIFY",
    slug: "fxify",
    domain: "fxify.com",
    logoUrl: favicon("fxify.com"),
    logoFallback: "FX",
    accent: "from-fuchsia-500 to-orange-400",
    score: 82,
    rating: 4.3,
    reviewCount: 4400,
    payout: "On demand",
    payoutFrequency: "On demand",
    maxDrawdown: "10%",
    dailyDrawdown: "5%",
    profitTarget: "10% / 5%",
    challengeFee: "$119",
    maxAccount: "$400k",
    country: "United Kingdom",
    markets: ["Forex", "Indices", "Commodities", "Crypto"],
    challengeTypes: ["One-step", "Two-step", "Three-step"],
    tags: ["Flexible", "Scaling", "CFDs"],
    verified: true,
    lastRuleUpdate: "2026-05-28",
    summary: "Flexible CFD funding brand with multiple evaluation formats and broad trader appeal."
  },
  {
    name: "City Traders Imperium",
    slug: "city-traders-imperium",
    domain: "citytradersimperium.com",
    logoUrl: favicon("citytradersimperium.com"),
    logoFallback: "CT",
    accent: "from-purple-500 to-blue-500",
    score: 80,
    rating: 4.2,
    reviewCount: 3300,
    payout: "Monthly",
    payoutFrequency: "Monthly",
    maxDrawdown: "5%",
    dailyDrawdown: "Plan based",
    profitTarget: "10%",
    challengeFee: "$139",
    maxAccount: "$4M scaling",
    country: "United Kingdom",
    markets: ["Forex", "Indices", "Commodities"],
    challengeTypes: ["Evaluation", "Instant funding"],
    tags: ["Scaling", "Education", "UK"],
    verified: true,
    lastRuleUpdate: "2026-04-22",
    summary: "A UK prop brand with education-heavy positioning and scaling-focused trader programs."
  },
  {
    name: "Maven Trading",
    slug: "maven-trading",
    domain: "maventrading.com",
    logoUrl: favicon("maventrading.com"),
    logoFallback: "MV",
    accent: "from-teal-400 to-blue-500",
    score: 78,
    rating: 4.1,
    reviewCount: 2800,
    payout: "Bi-weekly",
    payoutFrequency: "Bi-weekly",
    maxDrawdown: "10%",
    dailyDrawdown: "5%",
    profitTarget: "8% / 5%",
    challengeFee: "$69",
    maxAccount: "$200k",
    country: "Canada",
    markets: ["Forex", "Indices", "Commodities", "Crypto"],
    challengeTypes: ["One-step", "Two-step"],
    tags: ["Modern", "CFDs", "Promos"],
    verified: true,
    lastRuleUpdate: "2026-05-15",
    summary: "Modern prop firm with accessible pricing and broad market coverage."
  },
  {
    name: "BrightFunded",
    slug: "brightfunded",
    domain: "brightfunded.com",
    logoUrl: favicon("brightfunded.com"),
    logoFallback: "BF",
    accent: "from-yellow-300 to-cyan-400",
    score: 79,
    rating: 4.2,
    reviewCount: 3000,
    payout: "Bi-weekly",
    payoutFrequency: "Bi-weekly",
    maxDrawdown: "10%",
    dailyDrawdown: "5%",
    profitTarget: "8% / 5%",
    challengeFee: "$119",
    maxAccount: "$200k",
    country: "Netherlands",
    markets: ["Forex", "Indices", "Commodities", "Crypto"],
    challengeTypes: ["Two-step"],
    tags: ["EU", "Modern", "CFDs"],
    verified: true,
    lastRuleUpdate: "2026-06-02",
    summary: "European CFD evaluation firm with sleek branding and standard two-step challenge structures."
  },
  {
    name: "Funding Traders",
    slug: "funding-traders",
    domain: "fundingtraders.com",
    logoUrl: favicon("fundingtraders.com"),
    logoFallback: "FR",
    accent: "from-lime-400 to-emerald-600",
    score: 77,
    rating: 4.1,
    reviewCount: 2400,
    payout: "Bi-weekly",
    payoutFrequency: "Bi-weekly",
    maxDrawdown: "10%",
    dailyDrawdown: "5%",
    profitTarget: "8% / 5%",
    challengeFee: "$109",
    maxAccount: "$200k",
    country: "Global",
    markets: ["Forex", "Indices", "Commodities"],
    challengeTypes: ["One-step", "Two-step"],
    tags: ["CFDs", "Global", "Promos"],
    verified: true,
    lastRuleUpdate: "2026-05-12",
    summary: "Global CFD prop firm with accessible challenge structures and promotion-driven acquisition."
  },
  {
    name: "Skilled Funded Traders",
    slug: "skilled-funded-traders",
    domain: "skilledfundedtraders.com",
    logoUrl: favicon("skilledfundedtraders.com"),
    logoFallback: "SFT",
    accent: "from-violet-400 to-blue-500",
    score: 76,
    rating: 4.0,
    reviewCount: 2100,
    payout: "Bi-weekly",
    payoutFrequency: "Bi-weekly",
    maxDrawdown: "10%",
    dailyDrawdown: "5%",
    profitTarget: "8% / 5%",
    challengeFee: "$79",
    maxAccount: "$200k",
    country: "United States",
    markets: ["Forex", "Indices", "Commodities"],
    challengeTypes: ["One-step", "Two-step"],
    tags: ["CFDs", "Retail", "Flexible"],
    verified: true,
    lastRuleUpdate: "2026-04-18",
    summary: "Retail-focused challenge provider with familiar evaluation rules and broad accessibility."
  },
  {
    name: "Traddoo",
    slug: "traddoo",
    domain: "traddoo.com",
    logoUrl: favicon("traddoo.com"),
    logoFallback: "TD",
    accent: "from-cyan-400 to-emerald-500",
    score: 75,
    rating: 4.0,
    reviewCount: 1900,
    payout: "Bi-weekly",
    payoutFrequency: "Bi-weekly",
    maxDrawdown: "10%",
    dailyDrawdown: "5%",
    profitTarget: "8% / 5%",
    challengeFee: "$99",
    maxAccount: "$200k",
    country: "Global",
    markets: ["Forex", "Indices", "Commodities"],
    challengeTypes: ["One-step", "Two-step"],
    tags: ["CFDs", "Global", "Affordable"],
    verified: true,
    lastRuleUpdate: "2026-05-05",
    summary: "Accessible CFD prop firm with straightforward challenge options and global reach."
  },
  {
    name: "Funded Engineer",
    slug: "funded-engineer",
    domain: "fundedengineer.com",
    logoUrl: favicon("fundedengineer.com"),
    logoFallback: "FE",
    accent: "from-slate-300 to-blue-500",
    score: 74,
    rating: 3.9,
    reviewCount: 1700,
    payout: "Bi-weekly",
    payoutFrequency: "Bi-weekly",
    maxDrawdown: "10%",
    dailyDrawdown: "5%",
    profitTarget: "8% / 5%",
    challengeFee: "$99",
    maxAccount: "$200k",
    country: "Global",
    markets: ["Forex", "Indices", "Commodities"],
    challengeTypes: ["One-step", "Two-step"],
    tags: ["CFDs", "Evaluation", "Rules watch"],
    verified: true,
    lastRuleUpdate: "2026-03-30",
    summary: "Included for rule/history tracking because traders often search legacy and active-status firms."
  },
  {
    name: "Naira Trader",
    slug: "naira-trader",
    domain: "nairatrader.com",
    logoUrl: favicon("nairatrader.com"),
    logoFallback: "₦T",
    accent: "from-green-400 to-white",
    score: 74,
    rating: 4.0,
    reviewCount: 820,
    payout: "Weekly",
    payoutFrequency: "Weekly",
    maxDrawdown: "8%",
    dailyDrawdown: "4%",
    profitTarget: "8%",
    challengeFee: "USD pricing varies",
    maxAccount: "Regional plans",
    country: "Nigeria",
    markets: ["Forex", "Indices", "Commodities"],
    challengeTypes: ["Evaluation"],
    tags: ["Nigeria", "Local payments", "FX"],
    verified: false,
    lastRuleUpdate: "2026-06-01",
    summary: "Local-market entry reserved for Nigerian trader discovery, local payments and regional prop firm monitoring."
  }
];

export const featuredFirms = propFirms.slice(0, 8);

export const dashboardMetrics = [
  { label: "Published firms", value: String(propFirms.length), delta: "Source-reviewed profiles" },
  { label: "Broker profiles", value: String(brokers.length), delta: "Public-info checked" },
  { label: "Market data", value: "Unavailable", delta: "Provider feed required" },
  { label: "User alerts", value: "Account-only", delta: "Saved after sign-in" }
];

export const newsEvents = [
  {
    title: "Rule changes to review before buying a challenge",
    impact: "High",
    time: "Research watch",
    href: "/news-radar#rule-changes"
  },
  {
    title: "Gold volatility windows traders should respect",
    impact: "Medium",
    time: "Market context",
    href: "/news-radar#gold-volatility"
  },
  {
    title: "How payout proof should be checked before trusting claims",
    impact: "Low",
    time: "Trust framework",
    href: "/news-radar#payout-proof"
  }
];

export const routes = [
  { href: "/dashboard", label: "Dashboard" },
  { href: "/trader-dna", label: "Trader DNA" },
  { href: "/prop-firms", label: "Prop Firms" },
  { href: "/brokers", label: "Brokers" },
  { href: "/compare", label: "Compare" },
  { href: "/market-intelligence", label: "Market Intelligence" },
  { href: "/decision-engine", label: "Decision Engine" },
  { href: "/ai", label: "AI" },
  { href: "/spreads", label: "Spreads" },
  { href: "/gold", label: "Gold" },
  { href: "/news-radar", label: "News Radar" },
  { href: "/trader-connect", label: "Trader Connect" },
  { href: "/roadmap", label: "Product Updates" },
  { href: "/articles", label: "Articles" },
  { href: "/sources", label: "Sources" },
  { href: "/tools", label: "Tools" },
  { href: "/pricing", label: "Pricing" }
];
